### ISSUE TITLE
Wget e nano file

### ISSUE THREAD

**Issue by kirckc** [Ansuel/GUI_ipk#1]
Ciao Ansuel , sarebbe possibile compilare wget e nano per il repository della 2.1.x ?
grazie.

**Comment by Ansuel** [comment]
wget è già presente 
nano lo sto compilando ora

**Comment by kirckc** [comment]
giusto per fare un esempio .... se do 
wget https://repository.ilpuntotecnico.com/files/roleo/public/agtef/1.1.0/brcm63xx-tch/packages/packages/adblock_1.5.4-1_all.ipk
risponde 
Connecting to repository.ilpuntotecnico.com (104.31.77.58:443)
wget: error getting response: Connection reset by peer
perchè ?

**Comment by Ansuel** [comment]
è un problema del sito de il punto... con curl funziona bene (sicuramente problem con redirect)

in ogni caso perchè devi usare quel pacchetto? nel repository mio c'è già adblock...

**Comment by kirckc** [comment]
non mi serve quel pacchetto , era il primo che ho trovato, ma con tutti fa cosi' 

nano ? 

a quando ?

**Comment by kirckc** [comment]
> è un problema del sito de il punto... con curl funziona bene (sicuramente problem con redirect)
> 
> in ogni caso perchè devi usare quel pacchetto? nel repository mio c'è già adblock...

comunque con la 1.1.1 usavo tranquillamente wget con ilpunto....

**Comment by Ansuel** [comment]
sostituivamo il pacchetto ora teniamo quello normale

**Comment by kirckc** [comment]
Ciao, sei riuscito a compilarlo ?

**Comment by Ansuel** [comment]
Ciao scusa, a quanto pare nano ha problemi di compilazione... li ho reportati e aspetto respondo (credo sia un problema tra gcc vecchio e nano...) vim è sufficente?

**Comment by kirckc** [comment]
NON e' proprio la stessa cosa, cerca di farlo funzionare , grazie.

**Comment by Ansuel** [comment]
Aggiunto
