### ISSUE TITLE
Expand lists with other packages from OpenWrt

### ISSUE THREAD

**Issue by Petapton** [Ansuel/GUI_ipk#4]
Hi, I was wondering if you could include other packages in this repo which are in OpenWrt repo, but not in yours. I think users could benefit from using USB audio cards or arduino&co with such a powerful device.

**Comment by Ansuel** [comment]
pls list the package you need

**Comment by Petapton** [comment]
Yes, it's a bit tricky. I need to install shairport-sync, but it has a lot of dependencies...

**Comment by Ansuel** [comment]
dependencies get autocompiled...

**Comment by Petapton** [comment]
Uh, ok. I think most used (at least by me lolz) are shairport-sync, mpd and portaudio. Thank you :)

**Comment by Ansuel** [comment]
compiling...

**Comment by Petapton** [comment]
Uhh, thank you

**Comment by Ansuel** [comment]
mdp complain about not supported compiler...
portaudio and shairport np

**Comment by Petapton** [comment]
Hello, thanks a lot. Here is my bulletin:
Shairport is missing libconfig, so I can't install. Didn't check portaudio.
However I think it won't work, since we're still missing the whole audio subsystem (including kmod packages).
Last, you didn't update Packages and Packages.manifest, so I had to download and install ipks manually. Not really a problem, but not the best...

**Comment by Ansuel** [comment]
then i also need to know the kmod list

**Comment by Petapton** [comment]
They should be:
kmod-sound-core
kmod-usb-audio
Wow, I thought there were more of them. Anyway, don't forget libconfig

**Comment by Petapton** [comment]
UPDATE: Don't worry about them, I found them into the repo... Not sure about why.
Trying to install. I'll let you know.

**Comment by Petapton** [comment]
UPDATE 2: Did some research and found out that now I only need libconfig and alsa-utils (optionally with alsa-utils-test and alas-utils-seq). Also, if you can, please update manifest files.
Many thanks.

**Comment by Ansuel** [comment]
Can you tell me why you need libconfig?

Il Mer 25 Set 2019, 10:40 Petapton <notifications@github.com> ha scritto:

**Comment by Petapton** [comment]
It's a dependency for shairport:
```
Collected errors:
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for shairport-sync-openssl:
 * 	libconfig * 	libavahi-client * 	libsoxr * 
 * opkg_install_cmd: Cannot install package shairport-sync-openssl.
```

**Comment by Ansuel** [comment]
libconfig is actually already compiled...

**Comment by Ansuel** [comment]
@Petapton tell me the next problem :D

**Comment by Petapton** [comment]
And... YES!!
It got installed! But... I think we need to recompile the whole kernel, since when I try to catch some sound out of the USB interface, the system reboots. I suspect it's because kernel wasn't built with kmod-sound-core support, so...
## Let's compile the whole world again! 😬

**Comment by Ansuel** [comment]
erm :( we need crashlog anyway we can't recompile the kernel... all the firmware is signed

**Comment by Petapton** [comment]
Well, is it something I can provide?

**Comment by Petapton** [comment]
It doesn't let me list audio devices: seems a kernel compatibility issue

**Comment by Petapton** [comment]
Hi, I would also need kmod-fs-hfsplus as long as block-mount and netatalk. Thank you 😺

**Comment by tecufanujacu** [comment]
Please @Ansuel, could you compile the package haproxy?

**Comment by Suxsem** [comment]
Hi @Ansuel !
Can you please compile https-dns-proxy for the tg789vac v2?
I would like to enable dns-over-https on my router, thanks!

**Comment by Petapton** [comment]
@Suxsem I'm gonna close this issue since it's no more an issue. Ansuel released the build root and toolchain so anyone can build its own packages.
Please read [this](https://github.com/Ansuel/GUI_ipk/issues/7#issuecomment-592226987) post, where I explain how to do.

**Comment by Suxsem** [comment]
hi @Petapton thank you for your very useful post! I didn't noticed it.
I suggest you to pin it in the readme file.
Bye!

**Comment by Petapton** [comment]
I can't edit. @Ansuel should do it.
