### ISSUE TITLE
Upload SDK or build environment

### ISSUE THREAD

**Issue by Petapton** [Ansuel/GUI_ipk#9]
Hi, could you please upload Openwrt SDK you use to build packages or the whole buildenv?

**Comment by Ansuel** [comment]
If you mange to use it, can you post a guide in the issue to help the others?

**Comment by Petapton** [comment]
Lol, I just did. 
See #7

**Comment by Petapton** [comment]
It needs adjustments, but for now it should be enough. If you want you can edit and publish it in README.
